/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Edmundo
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 18/04/2013, 10:35:47 PM
 */

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author Alejo
 */
public class ejemplo extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    clase objetoClase = new clase();
    boolean lin =false;
    boolean cuadr =false;
    double cons =(double)5/(double)21;
    public ejemplo() {
        initComponents();
        jScrollPane1.getViewport().add(objetoClase);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        ax = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ax2 = new javax.swing.JTextField();
        bx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.SystemColor.window);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("X +");

        ax.setText("1");

        b.setText("0");

        jLabel2.setText("X^2 +");

        ax2.setText("1");

        bx.setText("0");

        jLabel3.setText("X +");

        c.setText("0");

        jButton1.setText("Grafica Lineal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Grafica Cuadratica");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ax, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ax2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(7, 7, 7)
                                .addComponent(bx, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ax2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
//        float trans=(float) 1;//0.5; 
//        com.sun.awt.AWTUtilities.setWindowOpacity(this, trans);
        //jButton1.setBackground(Color.red);
        
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lin=true;
        cuadr=false;
        objetoClase.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cuadr=true;
        lin=false;
        objetoClase.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    public class clase extends JPanel {

        public void paint(Graphics g) {
            super.paint(g);
            
            //g.drawLine(40, 40, 40, 460);//ordenada(y)
            g.drawLine(250, 40, 250, 460);//ordenada(y)
                    // x    y    x    y         
            //g.drawLine(40, 460, 800, 460);//absisa(x)
            g.drawLine(40, 250, 460, 250);//absisa(x)
            
            g.drawString(" 50", 215, 45);
            g.drawLine(245, 40, 255, 40);
            g.drawString(" 40", 215, 87);
            g.drawLine(245, 82, 255, 82);
            g.drawString(" 30", 215, 129);
            g.drawLine(245, 124, 255, 124);
            g.drawString(" 20", 215, 171);
            g.drawLine(245, 166, 255, 166);
            g.drawString(" 10", 215, 213);
            g.drawLine(245, 208, 255, 208);
            g.drawString("  0", 215, 255);
            g.drawLine(245, 250, 255, 250);
            g.drawString("-10", 215, 297);
            g.drawLine(245, 292, 255, 292);
            g.drawString("-20", 215, 339);
            g.drawLine(245, 334, 255, 334);
            g.drawString("-30", 215, 381);
            g.drawLine(245, 376, 255, 376);
            g.drawString("-40", 215, 423);
            g.drawLine(245, 418, 255, 418);
            g.drawString("-50", 215, 465);
            g.drawLine(245, 460, 255, 460);

            g.drawString("-50", 25, 270);
            g.drawLine(40, 245, 40, 255);
            g.drawString("-40", 67, 270);
            g.drawLine(82, 245, 82, 255);
            g.drawString("-30", 109, 270);
            g.drawLine(124, 245, 124, 255);
            g.drawString("-20", 151, 270);
            g.drawLine(166, 245, 166, 255);
            g.drawString("-10", 193, 270);
            g.drawLine(208, 245, 208, 255);
            g.drawString(" 0 ", 235, 270);
            g.drawLine(250, 245, 250, 255);
            g.drawString(" 10", 277, 270);
            g.drawLine(292, 245, 292, 255);
            g.drawString(" 20", 319, 270);
            g.drawLine(334, 245, 334, 255);
            g.drawString(" 30", 361, 270);
            g.drawLine(376, 245, 376, 255);
            g.drawString(" 40", 403, 270);
            g.drawLine(418, 245, 418, 255);
            g.drawString(" 50", 445, 270);
            g.drawLine(460, 245, 460, 255);
            
            g.setColor(Color.red);
            double x = -50;
            double x1 = -50;
            for (int i = 40; i < 460; i++) {
                if(i==40){
                    x= -50;
                    x1 = x+cons;
                }else{
                    x=x1;
                    x1 = x1+cons;
                }
                double ylin = yLin(x);
                double y1lin = yLin(x1);
                double yCuad = yCuad(x);
                double y1Cuad = yCuad(x1);
                if(lin)
                g.drawLine(i, yPix(ylin), i+1, yPix(y1lin));
                if(cuadr)
                g.drawLine(i, yPix(yCuad), i+1, yPix(y1Cuad));
                //double yCuad = yLin(x);
                
            }System.out.println("lo hizo");
            

        }
    }
    
    
    public int yPix(double y){
        int pixel= 250;
        if(y==0)
            pixel= 250;
        else if(y<0){
            float ypix = (float) (250+(y*(-1)/cons));
            pixel= Math.round(ypix);
        }else if(y>0){
            float ypix = (float) (250-(y/cons));
            pixel= Math.round(ypix);
        }
        return pixel;
    }
    
    public double yLin(double x){
        double y = (Integer.parseInt(ax.getText())*(x))+Integer.parseInt(b.getText());
        return y;
    }
    
    public double yCuad(double x){
        double y = (Integer.parseInt(ax2.getText())*(x*x))+(Integer.parseInt(bx.getText())*(x))+Integer.parseInt(c.getText());
        return y;
    }
    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ax;
    private javax.swing.JTextField ax2;
    private javax.swing.JTextField b;
    private javax.swing.JTextField bx;
    private javax.swing.JTextField c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
